import localFont from "@next/font/local";
import "./globals.css";

const euclid = localFont({
  src: [
    {
      path: "../../public/fonts/Euclid Circular B Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/Euclid Circular B Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-euclid",
});

export const metadata = {
  title: "myxellia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#fbfcfc" }} className={euclid.variable}>
        {children}
      </body>
    </html>
  );
}
